export const DELETE_STRINGS = 'DELETE_STRINGS'
export const ADD_STRING = 'ADD_STRING'

export const MARK_SINGLE_ROW = 'MARK_SINGLE_ROW'
export const MARK_NEXT_ROW = 'MARK_NEXT_ROW'
export const UN_MARK_SINGLE_ROW = 'UN_MARK_SINGLE_ROW'
export const UN_MARK_NEXT_ROW = 'UN_MARK_NEXT_ROW'

export const SORT_RESET = 'SORT_RESET'
export const SORT_ONE = 'SORT_ONE'
export const SORT_GROUP_ADD = 'SORT_GROUP_ADD'
export const SORT_GROUP_CHANGE = 'SORT_GROUP_CHANGE'
export const SORT_GROUP_REMOVE = 'SORT_GROUP_REMOVE'

export const FILTER_IF_ACTIVE = 'FILTER_IF_ACTIVE'
export const FILTER_BY_TEXT = 'FILTER_BY_TEXT'
export const FILTER_BY_DAYS = 'FILTER_BY_DAYS'
export const FILTER_OFF = 'FILTER_OFF'

export const PUT_OFFSET = 'PUT_OFFSET'
export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE'
export const VIRTUALIZE_TOGGLE = 'VIRTUALIZE_TOGGLE'

export const SHOW_COLUMN = 'SHOW_COLUMN'
